version: '2'

services:
  web:
    build: .
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    ports:
      - '5000:5000'
    links:
      - mongo

  mongo:
    image: mongo:3.0
    ports:
      - '27020:27020'
    volumes:
      - /data/db
